-- MySQL Script generated by MySQL Workbench
-- Sat Jul  9 20:11:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Cinemar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Cinemar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Cinemar` DEFAULT CHARACTER SET utf8 ;
USE `Cinemar` ;

-- -----------------------------------------------------
-- Table `Cinemar`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinemar`.`Rol` (
  `idRol` INT NOT NULL,
  `Rol` VARCHAR(45) NULL,
  `created_At` DATETIME NULL,
  `updated_At` DATETIME NULL,
  `deleted_At` DATETIME NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinemar`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinemar`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `Rol_idRol` INT NOT NULL,
  `Usuario` VARCHAR(45) NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Correo` VARCHAR(45) NULL,
  `Dni` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `idRol` INT NULL,
  `Frecuencia` TINYINT NULL,
  `Usuariocol` VARCHAR(45) NULL,
  `created_At` DATETIME NULL,
  `updated_At` DATETIME NULL,
  `deleted_At` DATETIME NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Rol_idx` (`Rol_idRol` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Rol`
    FOREIGN KEY (`Rol_idRol`)
    REFERENCES `Cinemar`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinemar`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinemar`.`Estado` (
  `idEstado` INT NOT NULL,
  `Estado` VARCHAR(45) NULL,
  `created_At` DATETIME NULL,
  `updated_At` DATETIME NULL,
  `deleted_At` DATETIME NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinemar`.`tipoPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinemar`.`tipoPago` (
  `idTipoPago` INT NOT NULL,
  `tipoPagocol` VARCHAR(45) NULL,
  `Tipo` VARCHAR(45) NULL,
  `created_At` DATETIME NULL,
  `updated_At` DATETIME NULL,
  `deleted_At` DATETIME NULL,
  PRIMARY KEY (`idTipoPago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinemar`.`Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinemar`.`Reserva` (
  `idReserva` INT NOT NULL,
  `Estado_idEstado1` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `tipoPago_idTipoPago1` INT NOT NULL,
  `created_At` DATETIME NULL,
  `updated_At` DATETIME NULL,
  `deleted_At` DATETIME NULL,
  PRIMARY KEY (`idReserva`),
  INDEX `fk_Reserva_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_Reserva_Estado1_idx` (`Estado_idEstado1` ASC) VISIBLE,
  INDEX `fk_Reserva_tipoPago1_idx` (`tipoPago_idTipoPago1` ASC) VISIBLE,
  CONSTRAINT `fk_Reserva_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Cinemar`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Estado1`
    FOREIGN KEY (`Estado_idEstado1`)
    REFERENCES `Cinemar`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_tipoPago1`
    FOREIGN KEY (`tipoPago_idTipoPago1`)
    REFERENCES `Cinemar`.`tipoPago` (`idTipoPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinemar`.`TipoSala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinemar`.`TipoSala` (
  `idTipoSala` INT NOT NULL,
  `Tipo` VARCHAR(45) NULL,
  `Precio` VARCHAR(45) NULL,
  `created_At` DATETIME NULL,
  `updated_At` DATETIME NULL,
  `deleted_At` DATETIME NULL,
  PRIMARY KEY (`idTipoSala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinemar`.`Sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinemar`.`Sala` (
  `idSala` INT NOT NULL,
  `TipoSala_idTipoSala` INT NOT NULL,
  `Capacidad` VARCHAR(45) NULL,
  `Nro` INT NULL,
  `created_At` DATETIME NULL,
  `updated_At` DATETIME NULL,
  `deleted_At` DATETIME NULL,
  PRIMARY KEY (`idSala`),
  INDEX `fk_Sala_TipoSala1_idx` (`TipoSala_idTipoSala` ASC) VISIBLE,
  CONSTRAINT `fk_Sala_TipoSala1`
    FOREIGN KEY (`TipoSala_idTipoSala`)
    REFERENCES `Cinemar`.`TipoSala` (`idTipoSala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinemar`.`Butaca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinemar`.`Butaca` (
  `idButaca` INT NOT NULL,
  `Sala_idSala` INT NOT NULL,
  `Nro` INT NULL,
  `created_At` DATETIME NULL,
  `updated_At` DATETIME NULL,
  `deleted_At` DATETIME NULL,
  PRIMARY KEY (`idButaca`),
  INDEX `fk_Butaca_Sala1_idx` (`Sala_idSala` ASC) VISIBLE,
  CONSTRAINT `fk_Butaca_Sala1`
    FOREIGN KEY (`Sala_idSala`)
    REFERENCES `Cinemar`.`Sala` (`idSala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinemar`.`Reserva_Detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinemar`.`Reserva_Detalle` (
  `idReserva_Detalle` INT NOT NULL,
  `Reserva_idReserva` INT NOT NULL,
  `Butaca_idButaca` INT NOT NULL,
  `created_At` DATETIME NULL,
  `updated_At` DATETIME NULL,
  `deleted_At` DATETIME NULL,
  PRIMARY KEY (`idReserva_Detalle`),
  INDEX `fk_Reserva_Detalle_Reserva1_idx` (`Reserva_idReserva` ASC) VISIBLE,
  INDEX `fk_Reserva_Detalle_Butaca1_idx` (`Butaca_idButaca` ASC) VISIBLE,
  CONSTRAINT `fk_Reserva_Detalle_Reserva1`
    FOREIGN KEY (`Reserva_idReserva`)
    REFERENCES `Cinemar`.`Reserva` (`idReserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_Detalle_Butaca1`
    FOREIGN KEY (`Butaca_idButaca`)
    REFERENCES `Cinemar`.`Butaca` (`idButaca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinemar`.`Genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinemar`.`Genero` (
  `idGenero` INT NOT NULL,
  `Genero` VARCHAR(45) NULL,
  `created_At` DATETIME NULL,
  `updated_At` DATETIME NULL,
  `deleted_At` DATETIME NULL,
  PRIMARY KEY (`idGenero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinemar`.`Pelicula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinemar`.`Pelicula` (
  `idPelicula` INT NOT NULL,
  `Genero_idGenero` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Duracion` VARCHAR(45) NULL,
  `atp` TINYINT NULL,
  `plus` VARCHAR(45) NULL,
  `created_At` DATETIME NULL,
  `updated_At` DATETIME NULL,
  `deleted_At` DATETIME NULL,
  PRIMARY KEY (`idPelicula`),
  INDEX `fk_Pelicula_Genero1_idx` (`Genero_idGenero` ASC) VISIBLE,
  CONSTRAINT `fk_Pelicula_Genero1`
    FOREIGN KEY (`Genero_idGenero`)
    REFERENCES `Cinemar`.`Genero` (`idGenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinemar`.`Cartelera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinemar`.`Cartelera` (
  `idCartelera` INT NOT NULL,
  `Sala_idSala` INT NOT NULL,
  `Pelicula_idPelicula` INT NOT NULL,
  `Fecha` DATE NULL,
  `Hora` TIME NULL,
  `PrecioTotal` VARCHAR(45) NULL,
  `created_At` DATETIME NULL,
  `updated_At` DATETIME NULL,
  `deleted_At` DATETIME NULL,
  PRIMARY KEY (`idCartelera`),
  INDEX `fk_Cartelera_Sala1_idx` (`Sala_idSala` ASC) VISIBLE,
  INDEX `fk_Cartelera_Pelicula1_idx` (`Pelicula_idPelicula` ASC) VISIBLE,
  CONSTRAINT `fk_Cartelera_Sala1`
    FOREIGN KEY (`Sala_idSala`)
    REFERENCES `Cinemar`.`Sala` (`idSala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cartelera_Pelicula1`
    FOREIGN KEY (`Pelicula_idPelicula`)
    REFERENCES `Cinemar`.`Pelicula` (`idPelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
